name: Pipeline Tugas 13 Automasi

on:
  push:
    branches: ["main", "master"]

jobs:
  tugas-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kode dari Repo
        uses: actions/checkout@v4

      - name: Eksekusi Pengecekan Secret
        run: |
          echo "Memulai validasi sistem..."
          echo "Nilai secret key saya adalah: ${{ secrets.MY_SECRET_KEY }}"
          echo "Pipeline berhasil dijalankan!"
